export const SIGNUP_COMPLETED = 'Signing up the user'
export const ADDED_COMPANY = 'User adds the company when signup'
export const LOGIN_DONE = 'User logs in the app'
export const LOGOUT = 'User logout from the app'
export const UNAUTHORIZATED = 'Unauthorizated request made'
export const RESET_SETTINGS = 'Reset Settings options'